# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created: Sat Feb  7 12:10:29 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("FrmDashboard")
        Form.resize(820, 547)
        Form.setWindowFilePath("")
        self.lblDashboard = QtGui.QLabel(Form)
        self.lblDashboard.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.lblDashboard.setFont(font)
        self.lblDashboard.setObjectName("lblDashboard")
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(120, 50, 566, 434))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnReproducir = QtGui.QPushButton(self.widget)
        self.btnReproducir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/reproducir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReproducir.setIcon(icon)
        self.btnReproducir.setIconSize(QtCore.QSize(170, 170))
        self.btnReproducir.setFlat(True)
        self.btnReproducir.setObjectName("btnReproducir")
        self.gridLayout.addWidget(self.btnReproducir, 0, 0, 1, 1)
        self.btnDescargas = QtGui.QPushButton(self.widget)
        self.btnDescargas.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/Descargas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDescargas.setIcon(icon1)
        self.btnDescargas.setIconSize(QtCore.QSize(176, 186))
        self.btnDescargas.setFlat(True)
        self.btnDescargas.setObjectName("btnDescargas")
        self.gridLayout.addWidget(self.btnDescargas, 0, 1, 1, 1)
        self.btnConfiguracion = QtGui.QPushButton(self.widget)
        self.btnConfiguracion.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/config2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfiguracion.setIcon(icon2)
        self.btnConfiguracion.setIconSize(QtCore.QSize(151, 151))
        self.btnConfiguracion.setFlat(True)
        self.btnConfiguracion.setObjectName("btnConfiguracion")
        self.gridLayout.addWidget(self.btnConfiguracion, 0, 2, 1, 1)
        self.lblReproductor = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblReproductor.setFont(font)
        self.lblReproductor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReproductor.setObjectName("lblReproductor")
        self.gridLayout.addWidget(self.lblReproductor, 1, 0, 1, 1)
        self.lblDescargas = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblDescargas.setFont(font)
        self.lblDescargas.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDescargas.setObjectName("lblDescargas")
        self.gridLayout.addWidget(self.lblDescargas, 1, 1, 1, 1)
        self.lblConfiguracion = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblConfiguracion.setFont(font)
        self.lblConfiguracion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConfiguracion.setObjectName("lblConfiguracion")
        self.gridLayout.addWidget(self.lblConfiguracion, 1, 2, 1, 1)
        self.btnCompartir = QtGui.QPushButton(self.widget)
        self.btnCompartir.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/compartir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCompartir.setIcon(icon3)
        self.btnCompartir.setIconSize(QtCore.QSize(170, 170))
        self.btnCompartir.setFlat(True)
        self.btnCompartir.setObjectName("btnCompartir")
        self.gridLayout.addWidget(self.btnCompartir, 2, 0, 1, 1)
        self.btnSugerencias = QtGui.QPushButton(self.widget)
        self.btnSugerencias.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/mensaje.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSugerencias.setIcon(icon4)
        self.btnSugerencias.setIconSize(QtCore.QSize(170, 170))
        self.btnSugerencias.setFlat(True)
        self.btnSugerencias.setObjectName("btnSugerencias")
        self.gridLayout.addWidget(self.btnSugerencias, 2, 1, 1, 1)
        self.btnIniciarSesionG = QtGui.QPushButton(self.widget)
        self.btnIniciarSesionG.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/googlePlus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIniciarSesionG.setIcon(icon5)
        self.btnIniciarSesionG.setIconSize(QtCore.QSize(170, 170))
        self.btnIniciarSesionG.setFlat(True)
        self.btnIniciarSesionG.setObjectName("btnIniciarSesionG")
        self.gridLayout.addWidget(self.btnIniciarSesionG, 2, 2, 1, 1)
        self.lblCompartir = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblCompartir.setFont(font)
        self.lblCompartir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCompartir.setObjectName("lblCompartir")
        self.gridLayout.addWidget(self.lblCompartir, 3, 0, 1, 1)
        self.lblSugerencias = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblSugerencias.setFont(font)
        self.lblSugerencias.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSugerencias.setObjectName("lblSugerencias")
        self.gridLayout.addWidget(self.lblSugerencias, 3, 1, 1, 1)
        self.lblIniciarSesion = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblIniciarSesion.setFont(font)
        self.lblIniciarSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIniciarSesion.setObjectName("lblIniciarSesion")
        self.gridLayout.addWidget(self.lblIniciarSesion, 3, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDashboard.setText(QtGui.QApplication.translate("Form", "Dashboard", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReproductor.setText(QtGui.QApplication.translate("Form", "Reproductor", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescargas.setText(QtGui.QApplication.translate("Form", "Descargas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConfiguracion.setText(QtGui.QApplication.translate("Form", "Configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCompartir.setText(QtGui.QApplication.translate("Form", "Compartir", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSugerencias.setText(QtGui.QApplication.translate("Form", "Sugerencias", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIniciarSesion.setText(QtGui.QApplication.translate("Form", "Iniciar Session", None, QtGui.QApplication.UnicodeUTF8))

