# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\juan.londono\Proyectos\PycharmProjects\juanes30-musica\ui\Dashboard.ui'
#
# Created: Sun Dec 11 20:11:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, FrmDashboard):
        FrmDashboard.setObjectName("FrmDashboard")
        FrmDashboard.resize(820, 547)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        FrmDashboard.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmDashboard.setWindowIcon(icon)
        FrmDashboard.setWindowFilePath("")
        self.lblDashboard = QtGui.QLabel(FrmDashboard)
        self.lblDashboard.setGeometry(QtCore.QRect(20, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.lblDashboard.setFont(font)
        self.lblDashboard.setObjectName("lblDashboard")
        self.layoutWidget = QtGui.QWidget(FrmDashboard)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 50, 566, 434))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnReproducir = QtGui.QPushButton(self.layoutWidget)
        self.btnReproducir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/reproducir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReproducir.setIcon(icon1)
        self.btnReproducir.setIconSize(QtCore.QSize(170, 170))
        self.btnReproducir.setFlat(True)
        self.btnReproducir.setObjectName("btnReproducir")
        self.gridLayout.addWidget(self.btnReproducir, 0, 0, 1, 1)
        self.btnDescargas = QtGui.QPushButton(self.layoutWidget)
        self.btnDescargas.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/Descargas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDescargas.setIcon(icon2)
        self.btnDescargas.setIconSize(QtCore.QSize(176, 186))
        self.btnDescargas.setFlat(True)
        self.btnDescargas.setObjectName("btnDescargas")
        self.gridLayout.addWidget(self.btnDescargas, 0, 1, 1, 1)
        self.btnConfiguracion = QtGui.QPushButton(self.layoutWidget)
        self.btnConfiguracion.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/config2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfiguracion.setIcon(icon3)
        self.btnConfiguracion.setIconSize(QtCore.QSize(151, 151))
        self.btnConfiguracion.setFlat(True)
        self.btnConfiguracion.setObjectName("btnConfiguracion")
        self.gridLayout.addWidget(self.btnConfiguracion, 0, 2, 1, 1)
        self.lblReproductor = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblReproductor.setFont(font)
        self.lblReproductor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReproductor.setObjectName("lblReproductor")
        self.gridLayout.addWidget(self.lblReproductor, 1, 0, 1, 1)
        self.lblDescargas = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblDescargas.setFont(font)
        self.lblDescargas.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDescargas.setObjectName("lblDescargas")
        self.gridLayout.addWidget(self.lblDescargas, 1, 1, 1, 1)
        self.lblConfiguracion = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblConfiguracion.setFont(font)
        self.lblConfiguracion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConfiguracion.setObjectName("lblConfiguracion")
        self.gridLayout.addWidget(self.lblConfiguracion, 1, 2, 1, 1)
        self.btnCompartir = QtGui.QPushButton(self.layoutWidget)
        self.btnCompartir.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/compartir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCompartir.setIcon(icon4)
        self.btnCompartir.setIconSize(QtCore.QSize(170, 170))
        self.btnCompartir.setFlat(True)
        self.btnCompartir.setObjectName("btnCompartir")
        self.gridLayout.addWidget(self.btnCompartir, 2, 0, 1, 1)
        self.btnSugerencias = QtGui.QPushButton(self.layoutWidget)
        self.btnSugerencias.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/mensaje.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSugerencias.setIcon(icon5)
        self.btnSugerencias.setIconSize(QtCore.QSize(170, 170))
        self.btnSugerencias.setFlat(True)
        self.btnSugerencias.setObjectName("btnSugerencias")
        self.gridLayout.addWidget(self.btnSugerencias, 2, 1, 1, 1)
        self.btnIniciarSesionG = QtGui.QPushButton(self.layoutWidget)
        self.btnIniciarSesionG.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/googlePlus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIniciarSesionG.setIcon(icon6)
        self.btnIniciarSesionG.setIconSize(QtCore.QSize(170, 170))
        self.btnIniciarSesionG.setFlat(True)
        self.btnIniciarSesionG.setObjectName("btnIniciarSesionG")
        self.gridLayout.addWidget(self.btnIniciarSesionG, 2, 2, 1, 1)
        self.lblCompartir = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblCompartir.setFont(font)
        self.lblCompartir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCompartir.setObjectName("lblCompartir")
        self.gridLayout.addWidget(self.lblCompartir, 3, 0, 1, 1)
        self.lblSugerencias = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblSugerencias.setFont(font)
        self.lblSugerencias.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSugerencias.setObjectName("lblSugerencias")
        self.gridLayout.addWidget(self.lblSugerencias, 3, 1, 1, 1)
        self.lblIniciarSesion = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lblIniciarSesion.setFont(font)
        self.lblIniciarSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIniciarSesion.setObjectName("lblIniciarSesion")
        self.gridLayout.addWidget(self.lblIniciarSesion, 3, 2, 1, 1)
        self.frame_2 = QtGui.QFrame(FrmDashboard)
        self.frame_2.setGeometry(QtCore.QRect(0, 510, 820, 41))
        self.frame_2.setStyleSheet("background-color: rgb(0,150,136);")
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_version = QtGui.QLabel(self.frame_2)
        self.label_version.setGeometry(QtCore.QRect(10, 0, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_version.setObjectName("label_version")
        self.label_bienvenido = QtGui.QLabel(FrmDashboard)
        self.label_bienvenido.setGeometry(QtCore.QRect(450, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_bienvenido.setFont(font)
        self.label_bienvenido.setObjectName("label_bienvenido")
        self.label_nombre_usuario = QtGui.QLabel(FrmDashboard)
        self.label_nombre_usuario.setGeometry(QtCore.QRect(560, 10, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_nombre_usuario.setFont(font)
        self.label_nombre_usuario.setObjectName("label_nombre_usuario")
        self.line = QtGui.QFrame(FrmDashboard)
        self.line.setGeometry(QtCore.QRect(17, 30, 791, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(FrmDashboard)
        QtCore.QMetaObject.connectSlotsByName(FrmDashboard)

    def retranslateUi(self, FrmDashboard):
        FrmDashboard.setWindowTitle(QtGui.QApplication.translate("FrmDashboard", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDashboard.setText(QtGui.QApplication.translate("FrmDashboard", "Dashboard", None, QtGui.QApplication.UnicodeUTF8))
        self.lblReproductor.setText(QtGui.QApplication.translate("FrmDashboard", "Reproductor", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescargas.setText(QtGui.QApplication.translate("FrmDashboard", "Descargas", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConfiguracion.setText(QtGui.QApplication.translate("FrmDashboard", "Configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCompartir.setText(QtGui.QApplication.translate("FrmDashboard", "Compartir", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSugerencias.setText(QtGui.QApplication.translate("FrmDashboard", "Sugerencias", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIniciarSesion.setText(QtGui.QApplication.translate("FrmDashboard", "Iniciar Session", None, QtGui.QApplication.UnicodeUTF8))
        self.label_version.setText(QtGui.QApplication.translate("FrmDashboard", "Version: 0.0.0, Este software se realiza con el fin de aprender python", None, QtGui.QApplication.UnicodeUTF8))
        self.label_bienvenido.setText(QtGui.QApplication.translate("FrmDashboard", "Bienvenido:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nombre_usuario.setText(QtGui.QApplication.translate("FrmDashboard", "Juan Londoño", None, QtGui.QApplication.UnicodeUTF8))

